### PR TITLE
Added the ability to install a custom tokenizer function.  (Same PR, different branch)

### PR DESCRIPTION
**Pull request by brucemack**
This would be useful for applications that have command syntaxes that can't be parsed by the simple space-delimited format supported by strtok_r(3).

This PR is identical to my other one, but this time I am using a branch called customTokenizer in my fork.  This may help to resolve an issue that Phil is having processing the PR.  

**Please use whichever PR is more convenient and decline the other one.**

### CODE REVIEW

**Comment by brucemack** [comment]
Yup, things are different now.  The unit tests are failing, which means that they are running. :-)  The failure is resulting from the fact that I am expecting EpoxyDuino (and specifically V1.0.0).  

The two options are (a) I change back to LinuxHostDuino (b) you change your Github workflow to use EpoxyDuino V1.0.0.  I'm fine either way, let me know what you want me to do.

**Comment by brucemack** [comment]
One other update.  I got a message back from Brian Parks and he has agreed to control the new EOL behavior change using a flag.  That's good news because it means that the new code will be compatible with your unit tests (any many other peoples' I suspect).  I will keep an eye out for his new release.

**Comment by philj404** [comment]
Continuing work from #12.  

I'm going to try reverting back to using the older "UnixHostDuino" (on my local branch) and see if that lets the tests pass.  If so, maybe we can worry about updating library dependencies later (at our convenience).

**Comment by bxparks** [comment]
Yeah, sorry for all the churn caused by the change in line termination in EpoxyDuino v1.1.0. As you saw, fixed in v1.2.0. The problem is, I have really no visibility in how my libraries are used..

**Comment by philj404** [comment]
@bxparks It's just one of those things that happens.

A stable library may not build very often.  Your client may not notice a breaking change until they do an unrelated push to their own code -- months later.

One way to catch this sooner is to just force a fresh build every week or so.  But then you need to pay attention to a failure at a random time. 

It's an argument for checking out a frozen versions of a libraries... but I'm not sure that's the right answer either.  I really do want security fixes!

**Comment by philj404** [comment]
@brucemack I had some cosmetic changes (code cleanup) on branch `test` and `next` which I should merge along with your changes.  I'm going to work that through with pull request #14.

This note is just to let you know I'm still working on it. 

After so much time I need to remember how to do a successful release.  So... I'm adding a checklist for releasing code, too.

Branch `test` should have your changes in it. 

I added a `NEW_LINE` macro to your `CustomParserTest.ino` to make it easier to switch between `"\n"` and `"\r\n"`. The flexibility may not be needed any more.  But I think it helps communicate the meaning of those special codes better anyway.  If you disagree, let me know and I can back out that change.

**Comment by brucemack** [comment]
Hi Phil, Happy New Year.  Checklist and NEW_LINE changes are both good ideas.

**Comment by philj404** [comment]
@brucemack I think I have merged your changes to `main` and created a new 0.2.3 release.  

Soon (tomorrow?) you should be able to pick it up from the Arduino IDE.  There were some merge conflicts (for EpoxyDuino<-> UnixHostDuino naming, and the NEW_LINE macro), but I think it's OK to ignore them.

Let me know if this works for you.  Thanks again for the contribution!

**Comment by brucemack** [comment]
Everything looks good, thanks for accepting my change.  I am closing this PR.  Have a good day.

**Pull request closed without merging**
