### PR TITLE
Providing the ability to supply a bit more help text, beyond just the name of the command.

### PR DESCRIPTION
**Pull request by brucemack**
This will make devices that leverage the shell more end-user-friendly.

### CODE REVIEW

**Comment by philj404** [comment]
@brucemack I am a bit concerned about increased RAM usage to support help text.  

This proposal increases the size of each SimpleSerialShell::Command by one pointer (about a 33% increase), even when there is no help text.  This is significant for an Arduino UNO, which only has 2k RAM.

I may be the only person who is still using the original platform, but I haven't given up on it yet.  (I understand my obsession may not be healthy, save me money or save me time.)

**Is there some way to avoid extra overhead on ALL commands, including legacy commands with no help text?**

Possible workarounds:
- for the commands that need extra hints, support a `-help` argument.
- When a command detects a syntax error, print out the appropriate help text.  For example the garbled command `motor 3storp` might return `motor: commands are 'motor stop' and 'motor start'`
- Add global `printMoreHelp` or `explain XYZ` commands and put the text there.
- Provide a paper "commands cheat sheet". This has zero overhead for the controller, supports graphics etc.  Just remember where you put the sheet.

**Comment by brucemack** [comment]
Good point, let me try something different.

**Comment by brucemack** [comment]
I've got one approach that involves a delimiter.  I'm using : for now.  So something like this addresses my use-case without any memory impact:

    shell.addCommand(F("range:<lower> <upper>"), rangeCommand);

Obviously, the Command::compareName() function is smart enough to ignore the documentation so that nothing breaks.

Would you be open to that?  I don't want to bother you with a PR if this concept is DOA.

Thanks, Bruce

**Comment by brucemack** [comment]
One other related question since you are obviously experienced architecting for small footprints.  

I've been told (in other contexts) to stay away from the Arduino String class in places where memory use really matters because of the risk of inefficient heap usage/fragmentation that can occur as a result of the realloc() activity.  You've got places in your code where there are Strings being created/destroyed a lot.  Does this matter?  My implementation removes the Strings, but I want to make sure I am not wasting my time.

Thanks for your help.

**Comment by philj404** [comment]
**Yes, you should be careful how you use String objects (or any objects)**, as they can break the allocation heap into unusable fragments.  This is a serious problem for code adding/removing objects a lot, if there is no garbage collection.  A good hint there may be a problem is if you use `new` and `delete` -- how do you _guarantee_ you will `delete` the object?  (Uh oh, better check... my usage is still looks OK...)

I use String in three different places in the code.  In each of these cases each String is a local variable (so no `new` or `delete`).  The fixed-size String _object_ is allocated on the stack, and the string's arbitrary-size _contents_ are on the heap.  But since these are local variables, when the function returns, the object and the heap contents are guaranteed freed up again.

So long as there is enough free contiguous memory on the heap to allocate the String in the first place, everything should be OK.  If something else has fragments the heap too much... that is trouble and this code may not work right.

**So... I may be using Strings safely, but do really I need to use them?**  

~~No~~ Maybe not.  Mostly I use them because in general I think they improve readability.  In fact, now that you point it out, they may not do much more than ensure that input character arrays are null-terminated -- that is a significant real-world problem!   (Addendum:  I think part of the reason I'm using Strings is because regular case comparison doesn't like to work directly with `__FlashStringHelper` pointers. String helps get ready for `strncasecmp()`.)

**The other code that uses the heap is the `new` call in addCommand()**.  These calls permanently allocate small pieces of the heap for each Command -- there is no associated `delete`.  I expect Commands to be added at startup, so hopefully they are all clustered at one end of the heap.  The rest of the (free) heap is still contiguous.

**Comment by philj404** [comment]
> I've got one approach that involves a delimiter. I'm using : for now. So something like this addresses my use-case without any memory impact:
>  `shell.addCommand(F("range:<lower> <upper>"), rangeCommand);`
>  Obviously, the Command::compareName() function is smart enough to ignore the documentation so that nothing breaks.

This looks promising.  It does not add RAM overhead to support the hints.  Legacy code is still compatible.

Would you need to modify help()?

(The cheat-sheet approach works for me, but that's mostly because I don't have that many commands -- or users.)

**Comment by brucemack** [comment]
Phil: Thanks for taking the time to write that informative reply on the String usage.  What you are saying makes a lot of sense.  strncasecmp_P() addresses your comment about the ability to compare between RAM and PROGMEM storage.  Sadly, EpoxyDuino is missing that function, but I'll PR that with Brian. :-)  I'll need that for another project anyhow.  Meanwhile, I will leave the Strings the way they are.

Yes, I modified help() and Command::compareName() to support my scheme.  

I've got nothing against cheat sheets (or yellow stickies!!), but I'm working on some multi-user projects that have several commands.  The picture below illustrates one help page that I'll be very happy to be able to reproduce (if possible) on your excellent shell.  

Do you mind if I PR a proposed change?  

Thanks again for all of your guidance.

Bruce

image

**Comment by philj404** [comment]
Yes, please submit the PR (this PR?).  Your cheat sheet provides a good example of when yellow stickies stop working :smile:.

It's useful to have the help text as close as possible to the associated command -- that makes it easier to remember to keep it current.

**Comment by brucemack** [comment]
Closing this one based on feedback from Phil on excessive memory footprint.  Another will follow.

**Pull request closed without merging**
